# Generated by Django 2.0.2 on 2020-02-09 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Llink',
            new_name='Link',
        ),
    ]
